name: Deploy to GitHub Pages

on:
  # 当 M9A 仓库文档更新时触发
  # Triggered when M9A repository docs are updated
  repository_dispatch:
    types: [md_changes]
  # 手动触发部署
  # Manually trigger deployment
  workflow_dispatch:
  # 推送到 main 分支时触发
  push:
    branches:
      - main

# 添加权限配置
permissions:
  contents: read
  pages: write
  id-token: write

# 只允许一个并发部署
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout M9A repository
        uses: actions/checkout@v4
        with:
          repository: MAA1999/M9A
          path: M9A-temp

      - name: Sync docs from M9A
        run: |
          # 同步根 README
          cp M9A-temp/docs/README.md docs/README.md || true
          # 同步中文文档
          rsync -av --delete M9A-temp/docs/zh_cn/ docs/zh_cn/ || true
          # 同步英文文档
          rsync -av --delete M9A-temp/docs/en_us/ docs/en_us/ || true

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build with VuePress
        run: pnpm run docs:build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vuepress/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
